DGIR-52: IP Range Restrictions Solr field & IP range restrictions filtering
discoverygarden/embargo pull request #24
Opened 2023-11-09 16:40 UTC by Prashant-bd

2024-01-11 13:18 UTC, bibliophileaxe requested changes

2024-01-12 12:32 UTC, Prashant-bd commented on src/Plugin/search_api/processor/EmbargoIpRestriction.php
> +      'label' => $this->t('Embargo IP'),
DOne.

2024-01-12 12:32 UTC, Prashant-bd commented on src/Plugin/search_api/processor/EmbargoIpRestriction.php
> +    $properties['exempt_users'] = new ProcessorProperty([
Done.

2024-01-12 12:32 UTC, Prashant-bd commented on src/Plugin/search_api/processor/EmbargoIpRestriction.php
> +    $properties['embargo_ip'] = new ProcessorProperty([
Done.

2024-01-12 12:32 UTC, Prashant-bd commented on src/Plugin/search_api/processor/EmbargoIpRestriction.php
> +class EmbargoIpRestriction extends ProcessorPluginBase implements ContainerFactoryPluginInterface {
Done

2024-01-12 12:32 UTC, Prashant-bd commented on src/Plugin/search_api/processor/EmbargoIpRestriction.php
> +      'description' => $this->t('Stores the Embargo IPs for filtering.'),
Done

2024-03-11 16:18 UTC, closed without merging